version: "3.7"
services:
  db:
    container_name: mongo-node-course
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=paulo
      - MONGO_INITDB_DATABASE=node-complete
      - MONGO_INITDB_ROOT_PASSWORD=penha269
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db