version: '3.5'

services:
  db:
    container_name: mysql_node_course
    image: mysql
    environment:
      MYSQL_USER: paulo
      MYSQL_PASSWORD: penha269
      MYSQL_ROOT_PASSWORD: penha269
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql: